# Generated by Django 2.1.3 on 2018-12-07 11:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('postCode', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=9)),
                ('description', models.CharField(max_length=700)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('bookIn', models.DateField(default=django.utils.timezone.now, verbose_name='Book in date')),
                ('bookOut', models.DateField(default=django.utils.timezone.now, verbose_name='Book out date')),
            ],
        ),
        migrations.CreateModel(
            name='Reserved_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('rented', models.BooleanField(default=False)),
                ('hotelName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('typeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='roomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room_type'),
        ),
        migrations.AddField(
            model_name='reserved_room',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='roomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room_type'),
        ),
    ]
